vich_uploader:
  db_driver: orm

  mappings:
    media_object:
      uri_prefix: /products
      upload_destination: "%kernel.project_dir%/public/products"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
